hex_name = require("hex_names")
hex_terrain = {}



-- 0108
local name = "0108"
hex_terrain[hex_name[name]] = "forest"
-- 0109
local name = "0109"
hex_terrain[hex_name[name]] = "broken"
-- 0110
local name = "0110"
hex_terrain[hex_name[name]] = "clear"
-- 0111
local name = "0111"
hex_terrain[hex_name[name]] = "broken"
-- 0112
local name = "0112"
hex_terrain[hex_name[name]] = "clear"
-- 0113
local name = "0113"
hex_terrain[hex_name[name]] = "woods"
-- 0114
local name = "0114"
hex_terrain[hex_name[name]] = "woods"
-- 0115
local name = "0115"
hex_terrain[hex_name[name]] = "woods"
-- 0116
local name = "0116"
hex_terrain[hex_name[name]] = "city"
-- 0117
local name = "0117"
hex_terrain[hex_name[name]] = "city"
-- 0118
local name = "0118"
hex_terrain[hex_name[name]] = "clear"
-- 0119
local name = "0119"
hex_terrain[hex_name[name]] = "clear"
-- 0120
local name = "0120"
hex_terrain[hex_name[name]] = "clear"
-- 0121
local name = "0121"
hex_terrain[hex_name[name]] = "woods"
-- 0122
local name = "0122"
hex_terrain[hex_name[name]] = "clear"
-- 0123
local name = "0123"
hex_terrain[hex_name[name]] = "clear"
-- 0124
local name = "0124"
hex_terrain[hex_name[name]] = "broken"
-- 0125
local name = "0125"
hex_terrain[hex_name[name]] = "broken"
-- 0126
local name = "0126"
hex_terrain[hex_name[name]] = "clear"
-- 0127
local name = "0127"
hex_terrain[hex_name[name]] = "clear"
-- 0128
local name = "0128"
hex_terrain[hex_name[name]] = "clear"
-- 0129
local name = "0129"
hex_terrain[hex_name[name]] = "clear"
-- 0130
local name = "0130"
hex_terrain[hex_name[name]] = "clear"


-- 0201
local name = "0201"
hex_terrain[hex_name[name]] = "forest"
-- 0202
local name = "0202"
hex_terrain[hex_name[name]] = "forest"
-- 0203
local name = "0203"
hex_terrain[hex_name[name]] = "forest"
-- 0204
local name = "0204"
hex_terrain[hex_name[name]] = "woods"
-- 0205
local name = "0205"
hex_terrain[hex_name[name]] = "broken"
-- 0206
local name = "0206"
hex_terrain[hex_name[name]] = "woods"
-- 0207
local name = "0207"
hex_terrain[hex_name[name]] = "forest"
-- 0208
local name = "0208"
hex_terrain[hex_name[name]] = "forest"
-- 0209
local name = "0209"
hex_terrain[hex_name[name]] = "forest"
-- 0210
local name = "0210"
hex_terrain[hex_name[name]] = "forest"
-- 0211
local name = "0211"
hex_terrain[hex_name[name]] = "woods"
-- 0212
local name = "0212"
hex_terrain[hex_name[name]] = "city"
-- 0213
local name = "0213"
hex_terrain[hex_name[name]] = "woods"
-- 0214
local name = "0214"
hex_terrain[hex_name[name]] = "woods"
-- 0215
local name = "0215"
hex_terrain[hex_name[name]] = "woods"
-- 0216
local name = "0216"
hex_terrain[hex_name[name]] = "broken"
-- 0217
local name = "0217"
hex_terrain[hex_name[name]] = "broken"
-- 0218
local name = "0218"
hex_terrain[hex_name[name]] = "broken"
-- 0219
local name = "0219"
hex_terrain[hex_name[name]] = "broken"
-- 0220
local name = "0220"
hex_terrain[hex_name[name]] = "broken"
-- 0221
local name = "0221"
hex_terrain[hex_name[name]] = "woods"
-- 0222
local name = "0222"
hex_terrain[hex_name[name]] = "clear"
-- 0223
local name = "0223"
hex_terrain[hex_name[name]] = "broken"
-- 0224
local name = "0224"
hex_terrain[hex_name[name]] = "clear"
-- 0225
local name = "0225"
hex_terrain[hex_name[name]] = "clear"
-- 0226
local name = "0226"
hex_terrain[hex_name[name]] = "clear"
-- 0227
local name = "0227"
hex_terrain[hex_name[name]] = "clear"
-- 0228
local name = "0228"
hex_terrain[hex_name[name]] = "broken"
-- 0229
local name = "0229"
hex_terrain[hex_name[name]] = "woods"




-- 0301
local name = "0301"
hex_terrain[hex_name[name]] = "broken"
-- 0302
local name = "0302"
hex_terrain[hex_name[name]] = "forest"
-- 0303
local name = "0303"
hex_terrain[hex_name[name]] = "woods"
-- 0304
local name = "0304"
hex_terrain[hex_name[name]] = "woods"
-- 0305
local name = "0305"
hex_terrain[hex_name[name]] = "forest"
-- 0306
local name = "0306"
hex_terrain[hex_name[name]] = "woods"
-- 0307
local name = "0307"
hex_terrain[hex_name[name]] = "broken"
-- 0308
local name = "0308"
hex_terrain[hex_name[name]] = "forest"
-- 0309
local name = "0309"
hex_terrain[hex_name[name]] = "forest"
-- 0310
local name = "0310"
hex_terrain[hex_name[name]] = "forest"
-- 0311
local name = "0311"
hex_terrain[hex_name[name]] = "woods"
-- 0312
local name = "0312"
hex_terrain[hex_name[name]] = "woods"
-- 0313
local name = "0313"
hex_terrain[hex_name[name]] = "broken"
-- 0314
local name = "0314"
hex_terrain[hex_name[name]] = "woods"
-- 0315
local name = "0315"
hex_terrain[hex_name[name]] = "woods"
-- 0316
local name = "0316"
hex_terrain[hex_name[name]] = "forest"
-- 0317
local name = "0317"
hex_terrain[hex_name[name]] = "broken"
-- 0318
local name = "0318"
hex_terrain[hex_name[name]] = "forest"
-- 0319
local name = "0319"
hex_terrain[hex_name[name]] = "broken"
-- 0320
local name = "0320"
hex_terrain[hex_name[name]] = "woods"
-- 0321
local name = "0321"
hex_terrain[hex_name[name]] = "woods"
-- 0322
local name = "0322"
hex_terrain[hex_name[name]] = "clear"
-- 0323
local name = "0323"
hex_terrain[hex_name[name]] = "woods"
-- 0324
local name = "0324"
hex_terrain[hex_name[name]] = "woods"
-- 0325
local name = "0325"
hex_terrain[hex_name[name]] = "clear"
-- 0326
local name = "0326"
hex_terrain[hex_name[name]] = "broken"
-- 0327
local name = "0327"
hex_terrain[hex_name[name]] = "clear"
-- 0328
local name = "0328"
hex_terrain[hex_name[name]] = "clear"
-- 0329
local name = "0329"
hex_terrain[hex_name[name]] = "woods"
-- 0330
local name = "0330"
hex_terrain[hex_name[name]] = "clear"


-- 0401
local name = "0401"
hex_terrain[hex_name[name]] = "woods"
-- 0402
local name = "0402"
hex_terrain[hex_name[name]] = "woods"
-- 0403
local name = "0403"
hex_terrain[hex_name[name]] = "woods"
-- 0404
local name = "0404"
hex_terrain[hex_name[name]] = "forest"
-- 0405
local name = "0405"
hex_terrain[hex_name[name]] = "broken"
-- 0406
local name = "0406"
hex_terrain[hex_name[name]] = "woods"
-- 0407
local name = "0407"
hex_terrain[hex_name[name]] = "clear"
-- 0408
local name = "0408"
hex_terrain[hex_name[name]] = "broken"
-- 0409
local name = "0409"
hex_terrain[hex_name[name]] = "forest"
-- 0410
local name = "0410"
hex_terrain[hex_name[name]] = "broken"
-- 0411
local name = "0411"
hex_terrain[hex_name[name]] = "broken"
-- 0412
local name = "0412"
hex_terrain[hex_name[name]] = "forest"
-- 0413
local name = "0413"
hex_terrain[hex_name[name]] = "woods"
-- 0414
local name = "0414"
hex_terrain[hex_name[name]] = "broken"
-- 0415
local name = "0415"
hex_terrain[hex_name[name]] = "woods"
-- 0416
local name = "0416"
hex_terrain[hex_name[name]] = "broken"
-- 0417
local name = "0417"
hex_terrain[hex_name[name]] = "broken"
-- 0418
local name = "0418"
hex_terrain[hex_name[name]] = "clear"
-- 0419
local name = "0419"
hex_terrain[hex_name[name]] = "woods"
-- 0420
local name = "0420"
hex_terrain[hex_name[name]] = "broken"
-- 0421
local name = "0421"
hex_terrain[hex_name[name]] = "woods"
-- 0422
local name = "0422"
hex_terrain[hex_name[name]] = "woods"
-- 0423
local name = "0423"
hex_terrain[hex_name[name]] = "broken"
-- 0424
local name = "0424"
hex_terrain[hex_name[name]] = "woods"
-- 0425
local name = "0425"
hex_terrain[hex_name[name]] = "woods"
-- 0426
local name = "0426"
hex_terrain[hex_name[name]] = "broken"
-- 0427
local name = "0427"
hex_terrain[hex_name[name]] = "clear"
-- 0428
local name = "0428"
hex_terrain[hex_name[name]] = "clear"
-- 0429
local name = "0429"
hex_terrain[hex_name[name]] = "clear"



-- 0501
local name = "0501"
hex_terrain[hex_name[name]] = "clear"
-- 0502
local name = "0502"
hex_terrain[hex_name[name]] = "clear"
-- 0503
local name = "0503"
hex_terrain[hex_name[name]] = "broken"
-- 0504
local name = "0504"
hex_terrain[hex_name[name]] = "forest"
-- 0505
local name = "0505"
hex_terrain[hex_name[name]] = "forest"
-- 0506
local name = "0506"
hex_terrain[hex_name[name]] = "forest"
-- 0507
local name = "0507"
hex_terrain[hex_name[name]] = "clear"
-- 0508
local name = "0508"
hex_terrain[hex_name[name]] = "broken"
-- 0509
local name = "0509"
hex_terrain[hex_name[name]] = "forest"
-- 0510
local name = "0510"
hex_terrain[hex_name[name]] = "woods"
-- 0511
local name = "0511"
hex_terrain[hex_name[name]] = "forest"
-- 0512
local name = "0512"
hex_terrain[hex_name[name]] = "broken"
-- 0513
local name = "0513"
hex_terrain[hex_name[name]] = "broken"
-- 0514
local name = "0514"
hex_terrain[hex_name[name]] = "woods"
-- 0515
local name = "0515"
hex_terrain[hex_name[name]] = "woods"
-- 0516
local name = "0516"
hex_terrain[hex_name[name]] = "broken"
-- 0517
local name = "0517"
hex_terrain[hex_name[name]] = "woods"
-- 0518
local name = "0518"
hex_terrain[hex_name[name]] = "woods"
-- 0519
local name = "0519"
hex_terrain[hex_name[name]] = "clear"
-- 0520
local name = "0520"
hex_terrain[hex_name[name]] = "woods"
-- 0521
local name = "0521"
hex_terrain[hex_name[name]] = "city"
-- 0522
local name = "0522"
hex_terrain[hex_name[name]] = "forest"
-- 0523
local name = "0523"
hex_terrain[hex_name[name]] = "woods"
-- 0524
local name = "0524"
hex_terrain[hex_name[name]] = "broken"
-- 0525
local name = "0525"
hex_terrain[hex_name[name]] = "broken"
-- 0526
local name = "0526"
hex_terrain[hex_name[name]] = "broken"
-- 0527
local name = "0527"
hex_terrain[hex_name[name]] = "city"
-- 0528
local name = "0528"
hex_terrain[hex_name[name]] = "woods"
-- 0529
local name = "0529"
hex_terrain[hex_name[name]] = "broken"
-- 0530
local name = "0530"
hex_terrain[hex_name[name]] = "clear"

-- 0601
local name = "0601"
hex_terrain[hex_name[name]] = "woods"
-- 0602
local name = "0602"
hex_terrain[hex_name[name]] = "forest"
-- 0603
local name = "0603"
hex_terrain[hex_name[name]] = "forest"
-- 0604
local name = "0604"
hex_terrain[hex_name[name]] = "woods"
-- 0605
local name = "0605"
hex_terrain[hex_name[name]] = "broken"
-- 0606
local name = "0606"
hex_terrain[hex_name[name]] = "broken"
-- 0607
local name = "0607"
hex_terrain[hex_name[name]] = "clear"
-- 0608
local name = "0608"
hex_terrain[hex_name[name]] = "forest"
-- 0609
local name = "0609"
hex_terrain[hex_name[name]] = "forest"
-- 0610
local name = "0610"
hex_terrain[hex_name[name]] = "forest"
-- 0611
local name = "0611"
hex_terrain[hex_name[name]] = "forest"
-- 0612
local name = "0612"
hex_terrain[hex_name[name]] = "forest"
-- 0613
local name = "0613"
hex_terrain[hex_name[name]] = "forest"
-- 0614
local name = "0614"
hex_terrain[hex_name[name]] = "broken"
-- 0615
local name = "0615"
hex_terrain[hex_name[name]] = "broken"
-- 0616
local name = "0616"
hex_terrain[hex_name[name]] = "woods"
-- 0617
local name = "0617"
hex_terrain[hex_name[name]] = "broken"
-- 0618
local name = "0618"
hex_terrain[hex_name[name]] = "forest"
-- 0619
local name = "0619"
hex_terrain[hex_name[name]] = "woods"
-- 0620
local name = "0620"
hex_terrain[hex_name[name]] = "broken"
-- 0621
local name = "0621"
hex_terrain[hex_name[name]] = "woods"
-- 0622
local name = "0622"
hex_terrain[hex_name[name]] = "woods"
-- 0623
local name = "0623"
hex_terrain[hex_name[name]] = "woods"
-- 0624
local name = "0624"
hex_terrain[hex_name[name]] = "woods"
-- 0625
local name = "0625"
hex_terrain[hex_name[name]] = "broken"
-- 0626
local name = "0626"
hex_terrain[hex_name[name]] = "city"
-- 0627
local name = "0627"
hex_terrain[hex_name[name]] = "woods"
-- 0628
local name = "0628"
hex_terrain[hex_name[name]] = "broken"
-- 0629
local name = "0629"
hex_terrain[hex_name[name]] = "woods"


-- 0701
local name = "0701"
hex_terrain[hex_name[name]] = "broken"
-- 0702
local name = "0702"
hex_terrain[hex_name[name]] = "broken"
-- 0703
local name = "0703"
hex_terrain[hex_name[name]] = "woods"
-- 0704
local name = "0704"
hex_terrain[hex_name[name]] = "forest"
-- 0705
local name = "0705"
hex_terrain[hex_name[name]] = "broken"
-- 0706
local name = "0706"
hex_terrain[hex_name[name]] = "broken"
-- 0707
local name = "0707"
hex_terrain[hex_name[name]] = "broken"
-- 0708
local name = "0708"
hex_terrain[hex_name[name]] = "broken"
-- 0709
local name = "0709"
hex_terrain[hex_name[name]] = "broken"
-- 0710
local name = "0710"
hex_terrain[hex_name[name]] = "forest"
-- 0711
local name = "0711"
hex_terrain[hex_name[name]] = "woods"
-- 0712
local name = "0712"
hex_terrain[hex_name[name]] = "woods"
-- 0713
local name = "0713"
hex_terrain[hex_name[name]] = "woods"
-- 0714
local name = "0714"
hex_terrain[hex_name[name]] = "forest"
-- 0715
local name = "0715"
hex_terrain[hex_name[name]] = "woods"
-- 0716
local name = "0716"
hex_terrain[hex_name[name]] = "clear"
-- 0717
local name = "0717"
hex_terrain[hex_name[name]] = "woods"
-- 0718
local name = "0718"
hex_terrain[hex_name[name]] = "woods"
-- 0719
local name = "0719"
hex_terrain[hex_name[name]] = "woods"
-- 0720
local name = "0720"
hex_terrain[hex_name[name]] = "woods"
-- 0721
local name = "0721"
hex_terrain[hex_name[name]] = "woods"
-- 0722
local name = "0722"
hex_terrain[hex_name[name]] = "clear"
-- 0723
local name = "0723"
hex_terrain[hex_name[name]] = "broken"
-- 0724
local name = "0724"
hex_terrain[hex_name[name]] = "woods"
-- 0725
local name = "0725"
hex_terrain[hex_name[name]] = "forest"
-- 0726
local name = "0726"
hex_terrain[hex_name[name]] = "forest"
-- 0727
local name = "0727"
hex_terrain[hex_name[name]] = "woods"
-- 0728
local name = "0728"
hex_terrain[hex_name[name]] = "woods"
-- 0729
local name = "0729"
hex_terrain[hex_name[name]] = "clear"
-- 0730
local name = "0730"
hex_terrain[hex_name[name]] = "clear"


-- 0801
local name = "0801"
hex_terrain[hex_name[name]] = "broken"
-- 0802
local name = "0802"
hex_terrain[hex_name[name]] = "woods"
-- 0803
local name = "0803"
hex_terrain[hex_name[name]] = "broken"
-- 0804
local name = "0804"
hex_terrain[hex_name[name]] = "forest"
-- 0805
local name = "0805"
hex_terrain[hex_name[name]] = "broken"
-- 0806
local name = "0806"
hex_terrain[hex_name[name]] = "broken"
-- 0807
local name = "0807"
hex_terrain[hex_name[name]] = "clear"
-- 0808
local name = "0808"
hex_terrain[hex_name[name]] = "forest"
-- 0809
local name = "0809"
hex_terrain[hex_name[name]] = "woods"
-- 0810
local name = "0810"
hex_terrain[hex_name[name]] = "woods"
-- 0811
local name = "0811"
hex_terrain[hex_name[name]] = "broken"
-- 0812
local name = "0812"
hex_terrain[hex_name[name]] = "forest"
-- 0813
local name = "0813"
hex_terrain["393c5c"] = "broken"
-- 0814
local name = "0814"
hex_terrain[hex_name[name]] = "forest"
-- 0815
local name = "0815"
hex_terrain[hex_name[name]] = "woods"
-- 0816
local name = "0816"
hex_terrain[hex_name[name]] = "broken"
-- 0817
local name = "0817"
hex_terrain[hex_name[name]] = "forest"
-- 0818
local name = "0818"
hex_terrain[hex_name[name]] = "woods"
-- 0819
local name = "0819"
hex_terrain[hex_name[name]] = "clear"
-- 0820
local name = "0820"
hex_terrain[hex_name[name]] = "clear"
-- 0821
local name = "0821"
hex_terrain[hex_name[name]] = "broken"
-- 0822
local name = "0822"
hex_terrain[hex_name[name]] = "clear"
-- 0823
local name = "0823"
hex_terrain[hex_name[name]] = "broken"
-- 0824
local name = "0824"
hex_terrain[hex_name[name]] = "broken"
-- 0825
local name = "0825"
hex_terrain[hex_name[name]] = "woods"
-- 0826
local name = "0826"
hex_terrain[hex_name[name]] = "forest"
-- 0827
local name = "0827"
hex_terrain[hex_name[name]] = "broken"
-- 0828
local name = "0828"
hex_terrain[hex_name[name]] = "clear"
-- 0829
local name = "0829"
hex_terrain[hex_name[name]] = "broken"


-- 0902
local name = "0902"
hex_terrain[hex_name[name]] = "forest"
-- 0903
local name = "0903"
hex_terrain[hex_name[name]] = "woods"
-- 0904
local name = "0904"
hex_terrain[hex_name[name]] = "clear"
-- 0905
local name = "0905"
hex_terrain[hex_name[name]] = "forest"
-- 0906
local name = "0906"
hex_terrain[hex_name[name]] = "forest"
-- 0907
local name = "0907"
hex_terrain[hex_name[name]] = "clear"
-- 0908
local name = "0908"
hex_terrain[hex_name[name]] = "broken"
-- 0909
local name = "0909"
hex_terrain[hex_name[name]] = "woods"
-- 0910
hex_terrain["585730"] = "woods"
-- 0911
hex_terrain["f37470"] = "forest"
-- 0912
hex_terrain["e2c7d6"] = "forest"
-- 0913
hex_terrain["d12a45"] = "forest"
-- 0914
local name = "0914"
hex_terrain["4b524c"] = "woods"
-- 0915
local name = "0915"
hex_terrain[hex_name[name]] = "forest"
-- 0916
local name = "0916"
hex_terrain[hex_name[name]] = "forest"
-- 0917
local name = "0917"
hex_terrain[hex_name[name]] = "woods"
-- 0918
local name = "0918"
hex_terrain[hex_name[name]] = "forest"
-- 0919
local name = "0919"
hex_terrain[hex_name[name]] = "woods"
-- 0920
local name = "0920"
hex_terrain[hex_name[name]] = "woods"
-- 0921
local name = "0921"
hex_terrain[hex_name[name]] = "broken"
-- 0922
local name = "0922"
hex_terrain[hex_name[name]] = "woods"
-- 0923
local name = "0923"
hex_terrain[hex_name[name]] = "broken"
-- 0924
local name = "0924"
hex_terrain[hex_name[name]] = "woods"
-- 0925
local name = "0925"
hex_terrain[hex_name[name]] = "forest"
-- 0926
local name = "0926"
hex_terrain[hex_name[name]] = "forest"
-- 0927
local name = "0927"
hex_terrain[hex_name[name]] = "forest"
-- 0928
local name = "0928"
hex_terrain[hex_name[name]] = "clear"
-- 0929
local name = "0929"
hex_terrain[hex_name[name]] = "clear"
-- 0930
local name = "0930"
hex_terrain[hex_name[name]] = "clear"


-- 1001
local name = "1001"
hex_terrain[hex_name[name]] = "broken"
-- 1002
local name = "1002"
hex_terrain[hex_name[name]] = "woods"
-- 1003
local name = "1003"
hex_terrain[hex_name[name]] = "forest"
-- 1004
local name = "1004"
hex_terrain[hex_name[name]] = "broken"
-- 1005
local name = "1005"
hex_terrain[hex_name[name]] = "forest"
-- 1006
local name = "1006"
hex_terrain[hex_name[name]] = "forest"
-- 1007
local name = "1007"
hex_terrain[hex_name[name]] = "clear"
-- 1008
local name = "1008"
hex_terrain[hex_name[name]] = "broken"
-- 1009
hex_terrain["5839d5"] = "clear"
-- 1010
hex_terrain["02bd93"] = "forest"
-- 1011
hex_terrain["9dc118"] = "forest"
-- 1012
hex_terrain["6cfeeb"] = "broken"
-- 1013
hex_terrain["b0f0fc"] = "forest"
-- 1014
local name = "1014"
hex_terrain["c6a041"] = "broken"
-- 1015
local name = "1015"
hex_terrain[hex_name[name]] = "broken"
-- 1016
local name = "1016"
hex_terrain[hex_name[name]] = "forest"
-- 1017
local name = "1017"
hex_terrain[hex_name[name]] = "woods"
-- 1018
local name = "1018"
hex_terrain[hex_name[name]] = "woods"
-- 1019
local name = "1019"
hex_terrain[hex_name[name]] = "woods"
-- 1020
local name = "1020"
hex_terrain[hex_name[name]] = "broken"
-- 1021
local name = "1021"
hex_terrain[hex_name[name]] = "woods"
-- 1022
local name = "1022"
hex_terrain[hex_name[name]] = "broken"
-- 1023
local name = "1023"
hex_terrain[hex_name[name]] = "woods"
-- 1024
local name = "1024"
hex_terrain[hex_name[name]] = "clear"
-- 1025
local name = "1025"
hex_terrain[hex_name[name]] = "broken"
-- 1026
local name = "1026"
hex_terrain[hex_name[name]] = "clear"
-- 1027
local name = "1027"
hex_terrain[hex_name[name]] = "broken"
-- 1028
local name = "1028"
hex_terrain[hex_name[name]] = "clear"
-- 1029
local name = "1029"
hex_terrain[hex_name[name]] = "woods"

---------------

local name = "1102"
hex_terrain[hex_name[name]] = "broken"
local name = "1103"
hex_terrain[hex_name[name]] = "woods"
local name = "1104"
hex_terrain[hex_name[name]] = "forest"
local name = "1105"
hex_terrain[hex_name[name]] = "broken"
local name = "1106"
hex_terrain[hex_name[name]] = "woods"
local name = "1107"
hex_terrain[hex_name[name]] = "woods"
local name = "1108"
hex_terrain[hex_name[name]] = "broken"
local name = "1109"
hex_terrain[hex_name[name]] = "broken"
-- 1110
hex_terrain["b3de30"] = "broken"
-- 1111
hex_terrain["598613"] = "forest"
-- 1112
hex_terrain["195d56"] = "woods"
--1113
hex_terrain["d93c33"] = "forest"
--1114
hex_terrain["14139c"] = "broken"
--1115
hex_terrain["aa20e6"] = "woods"
local name = "1116"
hex_terrain[hex_name[name]] = "forest"
local name = "1117"
hex_terrain[hex_name[name]] = "woods"
local name = "1118"
hex_terrain[hex_name[name]] = "woods"
local name = "1119"
hex_terrain[hex_name[name]] = "woods"
local name = "1120"
hex_terrain[hex_name[name]] = "woods"
local name = "1121"
hex_terrain[hex_name[name]] = "woods"
local name = "1122"
hex_terrain[hex_name[name]] = "woods"
local name = "1123"
hex_terrain[hex_name[name]] = "woods"
local name = "1124"
hex_terrain[hex_name[name]] = "woods"
local name = "1125"
hex_terrain[hex_name[name]] = "woods"
local name = "1126"
hex_terrain[hex_name[name]] = "broken"
local name = "1127"
hex_terrain[hex_name[name]] = "broken"
local name = "1128"
hex_terrain[hex_name[name]] = "broken"
local name = "1129"
hex_terrain[hex_name[name]] = "broken"
local name = "1130"
hex_terrain[hex_name[name]] = "clear"

local name = "1201"
hex_terrain[hex_name[name]] = "woods"
local name = "1202"
hex_terrain[hex_name[name]] = "broken"
local name = "1203"
hex_terrain[hex_name[name]] = "woods"
local name = "1204"
hex_terrain[hex_name[name]] = "forest"
local name = "1205"
hex_terrain[hex_name[name]] = "woods"
local name = "1206"
hex_terrain[hex_name[name]] = "forest"
local name = "1207"
hex_terrain[hex_name[name]] = "woods"
local name = "1208"
hex_terrain[hex_name[name]] = "broken"
-- 1209
hex_terrain["f76346"] = "clear"
-- 1210
hex_terrain["88168f"] = "broken"
-- 1211
hex_terrain["e463d6"] = "broken"
-- 1212
hex_terrain["bfbd8c"] = "broken"
-- 1213
hex_terrain["b970ef"] = "broken"
-- 1214
hex_terrain["a78fc0"] = "woods"
-- 1215
hex_terrain["57bb0d"] = "broken"
local name = "1216"
hex_terrain[hex_name[name]] = "forest"
local name = "1217"
hex_terrain[hex_name[name]] = "woods"
local name = "1218"
hex_terrain[hex_name[name]] = "forest"
local name = "1219"
hex_terrain[hex_name[name]] = "broken"
local name = "1220"
hex_terrain[hex_name[name]] = "forest"
local name = "1221"
hex_terrain[hex_name[name]] = "woods"
local name = "1222"
hex_terrain[hex_name[name]] = "broken"
local name = "1223"
hex_terrain[hex_name[name]] = "woods"
local name = "1224"
hex_terrain[hex_name[name]] = "woods"
local name = "1225"
hex_terrain[hex_name[name]] = "woods"
local name = "1226"
hex_terrain[hex_name[name]] = "broken"
local name = "1227"
hex_terrain[hex_name[name]] = "forest"
local name = "1228"
hex_terrain[hex_name[name]] = "forest"
local name = "1229"
hex_terrain[hex_name[name]] = "forest"

local name = "1302"
hex_terrain[hex_name[name]] = "clear"
local name = "1303"
hex_terrain[hex_name[name]] = "woods"
local name = "1304"
hex_terrain[hex_name[name]] = "forest"
local name = "1305"
hex_terrain[hex_name[name]] = "forest"
local name = "1306"
hex_terrain[hex_name[name]] = "broken"
local name = "1307"
hex_terrain[hex_name[name]] = "forest"
local name = "1308"
hex_terrain[hex_name[name]] = "forest"
local name = "1309"
hex_terrain[hex_name[name]] = "broken"
local name = "1310"
hex_terrain[hex_name[name]] = "clear"
-- 1311
hex_terrain["c5b010"] = "broken"
-- 1312
hex_terrain["d92e91"] = "forest"
-- 1313
hex_terrain["b6d331"] = "broken"
-- 1314
hex_terrain["290b1d"] = "forest"
-- 1315
hex_terrain["b4b0f5"] = "woods"
local name = "1316"
hex_terrain[hex_name[name]] = "woods"
local name = "1317"
hex_terrain[hex_name[name]] = "woods"
local name = "1318"
hex_terrain[hex_name[name]] = "broken"
local name = "1319"
hex_terrain[hex_name[name]] = "woods"
local name = "1320"
hex_terrain[hex_name[name]] = "woods"
local name = "1321"
hex_terrain[hex_name[name]] = "woods"
local name = "1322"
hex_terrain[hex_name[name]] = "broken"
local name = "1323"
hex_terrain[hex_name[name]] = "woods"
local name = "1324"
hex_terrain[hex_name[name]] = "forest"
local name = "1325"
hex_terrain[hex_name[name]] = "woods"
local name = "1326"
hex_terrain[hex_name[name]] = "broken"
local name = "1327"
hex_terrain[hex_name[name]] = "forest"
local name = "1328"
hex_terrain[hex_name[name]] = "woods"
local name = "1329"
hex_terrain[hex_name[name]] = "forest"
local name = "1330"
hex_terrain[hex_name[name]] = "clear"



local name = "1401"
hex_terrain[hex_name[name]] = "broken"
local name = "1402"
hex_terrain[hex_name[name]] = "broken"
local name = "1403"
hex_terrain[hex_name[name]] = "woods"
local name = "1404"
hex_terrain[hex_name[name]] = "broken"
local name = "1405"
hex_terrain[hex_name[name]] = "woods"
local name = "1406"
hex_terrain[hex_name[name]] = "broken"
local name = "1407"
hex_terrain[hex_name[name]] = "forest"
local name = "1408"
hex_terrain[hex_name[name]] = "broken"
local name = "1409"
hex_terrain[hex_name[name]] = "clear"
local name = "1410"
hex_terrain[hex_name[name]] = "broken"
-- 1411
hex_terrain["99c3ee"] = "woods"
-- 1412
hex_terrain["9b8f6a"] = "woods"
-- 1413
hex_terrain["b6cd88"] = "woods"
-- 1414
hex_terrain["70b0bd"] = "woods"
local name = "1415"
hex_terrain[hex_name[name]] = "woods"
local name = "1416"
hex_terrain[hex_name[name]] = "woods"
local name = "1417"
hex_terrain[hex_name[name]] = "forest"
local name = "1418"
hex_terrain[hex_name[name]] = "forest"
local name = "1419"
hex_terrain[hex_name[name]] = "clear"
local name = "1420"
hex_terrain[hex_name[name]] = "woods"
local name = "1421"
hex_terrain[hex_name[name]] = "broken"
local name = "1422"
hex_terrain[hex_name[name]] = "woods"
local name = "1423"
hex_terrain[hex_name[name]] = "woods"
local name = "1424"
hex_terrain[hex_name[name]] = "clear"
local name = "1425"
hex_terrain[hex_name[name]] = "woods"
local name = "1426"
hex_terrain[hex_name[name]] = "woods"
local name = "1427"
hex_terrain[hex_name[name]] = "broken"
local name = "1428"
hex_terrain[hex_name[name]] = "clear"
local name = "1429"
hex_terrain[hex_name[name]] = "clear"



local name = "1501"
hex_terrain[hex_name[name]] = "broken"
local name = "1502"
hex_terrain[hex_name[name]] = "forest"
local name = "1503"
hex_terrain[hex_name[name]] = "woods"
local name = "1504"
hex_terrain[hex_name[name]] = "woods"
local name = "1505"
hex_terrain[hex_name[name]] = "broken"
local name = "1506"
hex_terrain[hex_name[name]] = "broken"
local name = "1507"
hex_terrain[hex_name[name]] = "woods"
local name = "1508"
hex_terrain[hex_name[name]] = "woods"
local name = "1509"
hex_terrain[hex_name[name]] = "broken"
local name = "1510"
hex_terrain[hex_name[name]] = "broken"
local name = "1511"
hex_terrain[hex_name[name]] = "woods"
local name = "1512"
hex_terrain[hex_name[name]] = "woods"
local name = "1513"
hex_terrain[hex_name[name]] = "broken"
-- 1514
hex_terrain["6aafc5"] = "woods"
local name = "1515"
hex_terrain[hex_name[name]] = "woods"
local name = "1516"
hex_terrain[hex_name[name]] = "broken"
local name = "1517"
hex_terrain[hex_name[name]] = "broken"
local name = "1518"
hex_terrain[hex_name[name]] = "woods"
local name = "1519"
hex_terrain[hex_name[name]] = "forest"
local name = "1520"
hex_terrain[hex_name[name]] = "forest"
local name = "1521"
hex_terrain[hex_name[name]] = "broken"
local name = "1522"
hex_terrain[hex_name[name]] = "forest"
local name = "1523"
hex_terrain[hex_name[name]] = "broken"
local name = "1524"
hex_terrain[hex_name[name]] = "broken"
local name = "1525"
hex_terrain[hex_name[name]] = "broken"
local name = "1526"
hex_terrain[hex_name[name]] = "forest"
local name = "1527"
hex_terrain[hex_name[name]] = "woods"
local name = "1528"
hex_terrain[hex_name[name]] = "broken"
local name = "1529"
hex_terrain[hex_name[name]] = "broken"
local name = "1530"
hex_terrain[hex_name[name]] = "clear"


local name = "1601"
hex_terrain[hex_name[name]] = "woods"
local name = "1602"
hex_terrain[hex_name[name]] = "woods"
local name = "1603"
hex_terrain[hex_name[name]] = "woods"
local name = "1604"
hex_terrain[hex_name[name]] = "woods"
local name = "1605"
hex_terrain[hex_name[name]] = "clear"
local name = "1606"
hex_terrain[hex_name[name]] = "woods"
local name = "1607"
hex_terrain[hex_name[name]] = "woods"
local name = "1608"
hex_terrain[hex_name[name]] = "woods"
local name = "1609"
hex_terrain[hex_name[name]] = "broken"
local name = "1610"
hex_terrain[hex_name[name]] = "clear"
local name = "1611"
hex_terrain[hex_name[name]] = "broken"
local name = "1612"
hex_terrain[hex_name[name]] = "broken"
local name = "1613"
hex_terrain[hex_name[name]] = "broken"
local name = "1614"
hex_terrain[hex_name[name]] = "broken"
local name = "1615"
hex_terrain[hex_name[name]] = "woods"
local name = "1616"
hex_terrain[hex_name[name]] = "forest"
local name = "1617"
hex_terrain[hex_name[name]] = "woods"
local name = "1618"
hex_terrain[hex_name[name]] = "forest"
local name = "1619"
hex_terrain[hex_name[name]] = "forest"
local name = "1620"
hex_terrain[hex_name[name]] = "woods"
local name = "1621"
hex_terrain[hex_name[name]] = "woods"
local name = "1622"
hex_terrain[hex_name[name]] = "woods"
local name = "1623"
hex_terrain[hex_name[name]] = "woods"
local name = "1624"
hex_terrain[hex_name[name]] = "forest"
local name = "1625"
hex_terrain[hex_name[name]] = "forest"
local name = "1626"
hex_terrain[hex_name[name]] = "forest"
local name = "1627"
hex_terrain[hex_name[name]] = "forest"
local name = "1628"
hex_terrain[hex_name[name]] = "forest"
local name = "1629"
hex_terrain[hex_name[name]] = "forest"

local name = "1701"
hex_terrain[hex_name[name]] = "woods"
local name = "1702"
hex_terrain[hex_name[name]] = "broken"
local name = "1703"
hex_terrain[hex_name[name]] = "woods"
local name = "1704"
hex_terrain[hex_name[name]] = "woods"
local name = "1705"
hex_terrain[hex_name[name]] = "forest"
local name = "1706"
hex_terrain[hex_name[name]] = "woods"
local name = "1707"
hex_terrain[hex_name[name]] = "woods"
local name = "1708"
hex_terrain[hex_name[name]] = "broken"
local name = "1709"
hex_terrain[hex_name[name]] = "woods"
local name = "1710"
hex_terrain[hex_name[name]] = "forest"
local name = "1711"
hex_terrain[hex_name[name]] = "woods"
local name = "1712"
hex_terrain[hex_name[name]] = "woods"
local name = "1713"
hex_terrain[hex_name[name]] = "broken"
local name = "1714"
hex_terrain[hex_name[name]] = "woods"
local name = "1715"
hex_terrain[hex_name[name]] = "woods"
local name = "1716"
hex_terrain[hex_name[name]] = "woods"
local name = "1717"
hex_terrain[hex_name[name]] = "forest"
local name = "1718"
hex_terrain[hex_name[name]] = "woods"
local name = "1719"
hex_terrain[hex_name[name]] = "woods"
local name = "1720"
hex_terrain[hex_name[name]] = "forest"
local name = "1721"
hex_terrain[hex_name[name]] = "forest"
local name = "1722"
hex_terrain[hex_name[name]] = "forest"
local name = "1723"
hex_terrain[hex_name[name]] = "forest"
local name = "1724"
hex_terrain[hex_name[name]] = "forest"
local name = "1725"
hex_terrain[hex_name[name]] = "forest"
local name = "1726"
hex_terrain[hex_name[name]] = "woods"
local name = "1727"
hex_terrain[hex_name[name]] = "woods"
local name = "1728"
hex_terrain[hex_name[name]] = "forest"
local name = "1729"
hex_terrain[hex_name[name]] = "forest"

local name = "1801"
hex_terrain[hex_name[name]] = "woods"
local name = "1802"
hex_terrain[hex_name[name]] = "broken"
local name = "1803"
hex_terrain[hex_name[name]] = "woods"
local name = "1804"
hex_terrain[hex_name[name]] = "woods"
local name = "1805"
hex_terrain[hex_name[name]] = "woods"
local name = "1806"
hex_terrain[hex_name[name]] = "woods"
local name = "1807"
hex_terrain[hex_name[name]] = "woods"
local name = "1808"
hex_terrain[hex_name[name]] = "broken"
local name = "1809"
hex_terrain[hex_name[name]] = "woods"
local name = "1810"
hex_terrain[hex_name[name]] = "forest"
local name = "1811"
hex_terrain[hex_name[name]] = "woods"
local name = "1812"
hex_terrain[hex_name[name]] = "forest"
local name = "1813"
hex_terrain[hex_name[name]] = "broken"
local name = "1814"
hex_terrain[hex_name[name]] = "broken"
local name = "1815"
hex_terrain[hex_name[name]] = "broken"
local name = "1816"
hex_terrain[hex_name[name]] = "clear"
local name = "1817"
hex_terrain[hex_name[name]] = "forest"
local name = "1818"
hex_terrain[hex_name[name]] = "woods"
local name = "1819"
hex_terrain[hex_name[name]] = "woods"
local name = "1820"
hex_terrain[hex_name[name]] = "woods"
local name = "1821"
hex_terrain[hex_name[name]] = "broken"
local name = "1822"
hex_terrain[hex_name[name]] = "forest"
local name = "1823"
hex_terrain[hex_name[name]] = "woods"
local name = "1824"
hex_terrain[hex_name[name]] = "forest"
local name = "1825"
hex_terrain[hex_name[name]] = "broken"
local name = "1826"
hex_terrain[hex_name[name]] = "broken"
local name = "1827"
hex_terrain[hex_name[name]] = "broken"


local name = "1901"
hex_terrain[hex_name[name]] = "clear"
local name = "1902"
hex_terrain[hex_name[name]] = "clear"
local name = "1903"
hex_terrain[hex_name[name]] = "broken"
local name = "1904"
hex_terrain[hex_name[name]] = "broken"
local name = "1905"
hex_terrain[hex_name[name]] = "woods"
local name = "1906"
hex_terrain[hex_name[name]] = "forest"
local name = "1907"
hex_terrain[hex_name[name]] = "woods"
local name = "1908"
hex_terrain[hex_name[name]] = "broken"
local name = "1909"
hex_terrain[hex_name[name]] = "woods"
local name = "1910"
hex_terrain[hex_name[name]] = "woods"
local name = "1911"
hex_terrain[hex_name[name]] = "broken"
local name = "1912"
hex_terrain[hex_name[name]] = "woods"
local name = "1913"
hex_terrain[hex_name[name]] = "forest"
local name = "1914"
hex_terrain[hex_name[name]] = "broken"
local name = "1915"
hex_terrain[hex_name[name]] = "broken"
local name = "1916"
hex_terrain[hex_name[name]] = "clear"
local name = "1917"
hex_terrain[hex_name[name]] = "woods"
local name = "1918"
hex_terrain[hex_name[name]] = "broken"
local name = "1919"
hex_terrain[hex_name[name]] = "woods"
local name = "1920"
hex_terrain[hex_name[name]] = "forest"
local name = "1921"
hex_terrain[hex_name[name]] = "forest"
local name = "1922"
hex_terrain[hex_name[name]] = "woods"
local name = "1923"
hex_terrain[hex_name[name]] = "broken"
local name = "1924"
hex_terrain[hex_name[name]] = "woods"
local name = "1925"
hex_terrain[hex_name[name]] = "broken"
local name = "1926"
hex_terrain[hex_name[name]] = "woods"

local name = "2001"
hex_terrain[hex_name[name]] = "clear"
local name = "2002"
hex_terrain[hex_name[name]] = "clear"
local name = "2003"
hex_terrain[hex_name[name]] = "broken"
local name = "2004"
hex_terrain[hex_name[name]] = "woods"
local name = "2005"
hex_terrain[hex_name[name]] = "clear"
local name = "2006"
hex_terrain[hex_name[name]] = "woods"
local name = "2007"
hex_terrain[hex_name[name]] = "broken"
local name = "2008"
hex_terrain[hex_name[name]] = "woods"
local name = "2009"
hex_terrain[hex_name[name]] = "forest"
local name = "2010"
hex_terrain[hex_name[name]] = "woods"
local name = "2011"
hex_terrain[hex_name[name]] = "woods"
local name = "2012"
hex_terrain[hex_name[name]] = "forest"
local name = "2013"
hex_terrain[hex_name[name]] = "woods"
local name = "2014"
hex_terrain[hex_name[name]] = "broken"
local name = "2015"
hex_terrain[hex_name[name]] = "woods"
local name = "2016"
hex_terrain[hex_name[name]] = "clear"
local name = "2017"
hex_terrain[hex_name[name]] = "woods"
local name = "2018"
hex_terrain[hex_name[name]] = "broken"
local name = "2019"
hex_terrain[hex_name[name]] = "woods"
local name = "2020"
hex_terrain[hex_name[name]] = "woods"
local name = "2021"
hex_terrain[hex_name[name]] = "broken"
local name = "2022"
hex_terrain[hex_name[name]] = "woods"
local name = "2023"
hex_terrain[hex_name[name]] = "broken"
local name = "2024"
hex_terrain[hex_name[name]] = "broken"

local name = "2101"
hex_terrain[hex_name[name]] = "clear"
local name = "2102"
hex_terrain[hex_name[name]] = "clear"
local name = "2103"
hex_terrain[hex_name[name]] = "woods"
local name = "2104"
hex_terrain[hex_name[name]] = "woods"
local name = "2105"
hex_terrain[hex_name[name]] = "broken"
local name = "2106"
hex_terrain[hex_name[name]] = "woods"
local name = "2107"
hex_terrain[hex_name[name]] = "woods"
local name = "2108"
hex_terrain[hex_name[name]] = "broken"
local name = "2109"
hex_terrain[hex_name[name]] = "woods"
local name = "2110"
hex_terrain[hex_name[name]] = "woods"
local name = "2111"
hex_terrain[hex_name[name]] = "woods"
local name = "2112"
hex_terrain[hex_name[name]] = "forest"
local name = "2113"
hex_terrain[hex_name[name]] = "forest"
local name = "2114"
hex_terrain[hex_name[name]] = "woods"
local name = "2115"
hex_terrain[hex_name[name]] = "broken"
local name = "2116"
hex_terrain[hex_name[name]] = "clear"
local name = "2117"
hex_terrain[hex_name[name]] = "woods"
local name = "2118"
hex_terrain[hex_name[name]] = "clear"
local name = "2119"
hex_terrain[hex_name[name]] = "woods"
local name = "2120"
hex_terrain[hex_name[name]] = "forest"
local name = "2121"
hex_terrain[hex_name[name]] = "forest"
local name = "2122"
hex_terrain[hex_name[name]] = "broken"
local name = "2123"
hex_terrain[hex_name[name]] = "broken"

local name = "2201"
hex_terrain[hex_name[name]] = "broken"
local name = "2202"
hex_terrain[hex_name[name]] = "woods"
local name = "2203"
hex_terrain[hex_name[name]] = "broken"
local name = "2204"
hex_terrain[hex_name[name]] = "woods"
local name = "2205"
hex_terrain[hex_name[name]] = "forest"
local name = "2206"
hex_terrain[hex_name[name]] = "forest"
local name = "2207"
hex_terrain[hex_name[name]] = "broken"
local name = "2208"
hex_terrain[hex_name[name]] = "broken"
local name = "2209"
hex_terrain[hex_name[name]] = "broken"
local name = "2210"
hex_terrain[hex_name[name]] = "clear"
local name = "2211"
hex_terrain[hex_name[name]] = "woods"
local name = "2212"
hex_terrain[hex_name[name]] = "forest"
local name = "2213"
hex_terrain[hex_name[name]] = "woods"
local name = "2214"
hex_terrain[hex_name[name]] = "broken"
local name = "2215"
hex_terrain[hex_name[name]] = "woods"
local name = "2216"
hex_terrain[hex_name[name]] = "woods"
local name = "2217"
hex_terrain[hex_name[name]] = "woods"
local name = "2218"
hex_terrain[hex_name[name]] = "broken"
local name = "2219"
hex_terrain[hex_name[name]] = "woods"
local name = "2220"
hex_terrain[hex_name[name]] = "woods"
local name = "2221"
hex_terrain[hex_name[name]] = "forest"

local name = "2301"
hex_terrain[hex_name[name]] = "broken"
local name = "2302"
hex_terrain[hex_name[name]] = "woods"
local name = "2303"
hex_terrain[hex_name[name]] = "broken"
local name = "2304"
hex_terrain[hex_name[name]] = "woods"
local name = "2305"
hex_terrain[hex_name[name]] = "forest"
local name = "2306"
hex_terrain[hex_name[name]] = "woods"
local name = "2307"
hex_terrain[hex_name[name]] = "woods"
local name = "2308"
hex_terrain[hex_name[name]] = "woods"
local name = "2309"
hex_terrain[hex_name[name]] = "broken"
local name = "2310"
hex_terrain[hex_name[name]] = "clear"
local name = "2311"
hex_terrain[hex_name[name]] = "woods"
local name = "2312"
hex_terrain[hex_name[name]] = "woods"
local name = "2313"
hex_terrain[hex_name[name]] = "broken"
local name = "2314"
hex_terrain[hex_name[name]] = "broken"
local name = "2315"
hex_terrain[hex_name[name]] = "forest"
local name = "2316"
hex_terrain[hex_name[name]] = "woods"
local name = "2317"
hex_terrain[hex_name[name]] = "woods"
local name = "2318"
hex_terrain[hex_name[name]] = "broken"
local name = "2319"
hex_terrain[hex_name[name]] = "woods"
local name = "2320"
hex_terrain[hex_name[name]] = "broken"

local name = "2401"
hex_terrain[hex_name[name]] = "broken"
local name = "2402"
hex_terrain[hex_name[name]] = "broken"
local name = "2403"
hex_terrain[hex_name[name]] = "broken"
local name = "2404"
hex_terrain[hex_name[name]] = "broken"
local name = "2405"
hex_terrain[hex_name[name]] = "woods"
local name = "2406"
hex_terrain[hex_name[name]] = "broken"
local name = "2407"
hex_terrain[hex_name[name]] = "broken"
local name = "2408"
hex_terrain[hex_name[name]] = "broken"
local name = "2409"
hex_terrain[hex_name[name]] = "broken"
local name = "2410"
hex_terrain[hex_name[name]] = "woods"
local name = "2411"
hex_terrain[hex_name[name]] = "woods"
local name = "2412"
hex_terrain[hex_name[name]] = "broken"
local name = "2413"
hex_terrain[hex_name[name]] = "woods"
local name = "2414"
hex_terrain[hex_name[name]] = "broken"
local name = "2415"
hex_terrain[hex_name[name]] = "clear"
local name = "2416"
hex_terrain[hex_name[name]] = "woods"
local name = "2417"
hex_terrain[hex_name[name]] = "woods"
local name = "2418"
hex_terrain[hex_name[name]] = "woods"
local name = "2419"
hex_terrain[hex_name[name]] = "woods"

local name = "2501"
hex_terrain[hex_name[name]] = "broken"
local name = "2502"
hex_terrain[hex_name[name]] = "forest"
local name = "2503"
hex_terrain[hex_name[name]] = "woods"
local name = "2504"
hex_terrain[hex_name[name]] = "broken"
local name = "2505"
hex_terrain[hex_name[name]] = "clear"
local name = "2506"
hex_terrain[hex_name[name]] = "broken"
local name = "2507"
hex_terrain[hex_name[name]] = "clear"
local name = "2508"
hex_terrain[hex_name[name]] = "clear"
local name = "2509"
hex_terrain[hex_name[name]] = "broken"
local name = "2510"
hex_terrain[hex_name[name]] = "woods"
local name = "2511"
hex_terrain[hex_name[name]] = "broken"
local name = "2512"
hex_terrain[hex_name[name]] = "broken"
local name = "2513"
hex_terrain[hex_name[name]] = "broken"
local name = "2514"
hex_terrain[hex_name[name]] = "clear"
local name = "2515"
hex_terrain[hex_name[name]] = "broken"
local name = "2516"
hex_terrain[hex_name[name]] = "forest"
local name = "2517"
hex_terrain[hex_name[name]] = "forest"
local name = "2518"
hex_terrain[hex_name[name]] = "forest"
local name = "2519"
hex_terrain[hex_name[name]] = "forest"


local name = "2603"
hex_terrain[hex_name[name]] = "woods"
local name = "2604"
hex_terrain[hex_name[name]] = "woods"
local name = "2605"
hex_terrain[hex_name[name]] = "woods"
local name = "2606"
hex_terrain[hex_name[name]] = "clear"
local name = "2607"
hex_terrain[hex_name[name]] = "woods"
local name = "2608"
hex_terrain[hex_name[name]] = "forest"
local name = "2609"
hex_terrain[hex_name[name]] = "woods"
local name = "2610"
hex_terrain[hex_name[name]] = "woods"
local name = "2611"
hex_terrain[hex_name[name]] = "woods"
local name = "2612"
hex_terrain[hex_name[name]] = "city"
local name = "2613"
hex_terrain[hex_name[name]] = "woods"
local name = "2614"
hex_terrain[hex_name[name]] = "clear"
local name = "2615"
hex_terrain[hex_name[name]] = "clear"
local name = "2616"
hex_terrain[hex_name[name]] = "broken"
local name = "2617"
hex_terrain[hex_name[name]] = "woods"




return hex_terrain
